# Configuration Settings for C94-M8P device
ublox_gps_node1:
  ublox_gps_node:
    ros__parameters:
      debug: 0                    # Range 0-4 (0 means no debug statements will print)
      device: /dev/ttyUSB0
      frame_id: gps1
      uart1:
        baudrate: 38400

      tmode3: 0 #0 for disabled, 1 for survey-in, 2 for fixed (used for base station i think)

      #1 for rtk float, 2 for rtk fixed
      #dgnss_mode: 2