ublox_gps_node_rover_0:
  ros__parameters:
    debug: 1                    # Range 0-4 (0 means no debug statements will print)
    device: /dev/ttyRover
    frame_id: gps_rover
    hpg_reference: false
    uart1:
      baudrate: 115200
    nav_rate: 1
    rate: 1.0

    tmode3: 0 #0 for disabled, 1 for survey-in, 2 for fixed (used for base station i think)

    #1 for rtk float, 2 for rtk fixed
    #dgnss_mode: 2
    gnss:
      gps: true
      glonass: true
      galileo: true
      beidou: true
      qzss: true

    publish:
      # rxm:
      #   rtcm: True
      nav:
        relposned: true